create table Users(
user_id int generated by default as identity (start with 101 increment by 100) unique primary key,
user_role varchar(20)check(user_role = 'employee' or user_role = 'manager'),
email varchar(50),
firstName varchar(25),
lastName varchar(25),
password varchar(15),
userName varchar(25) unique
);



create table Reimbursement(
reimbursement_id serial primary key unique not null,
accepted varchar(3) check(accepted = 'yes' or accepted = 'no'),
amount numeric,
description varchar(225),
reimbursement_type varchar(50),
resolvetime timestamp,
resolved varchar(3) check(resolved = 'yes' or resolved = 'no'),
sumbit_time timestamp,
author_id int,
resolved_id int,
constraint reimbursement_author_id_fk
foreign key (author_id) references users(user_id),
constraint reimbursement_resolved_id_fk 
foreign key (resolved_id) references users(user_id)
);




